// Package template 提供日志字段代码生成的模板定义
package template

import (
	"strings"
	"text/template"

	"github.com/yuan-shuo/zerotele/internal/config"
)

// LogFieldsTemplate 是生成日志字段代码的模板字符串
const LogFieldsTemplate = `// Code generated by zerotele; DO NOT EDIT.
// zerotele {{ .Version }}

package {{ .PackageName }}

import (
	"context"
	"sort"

	"github.com/zeromicro/go-zero/core/logc"
	"github.com/zeromicro/go-zero/core/logx"
)

// fieldKeys 日志字段名常量（与类型名保持一致）
var fieldKeys = struct {
{{- range .LogFields }}
	{{ .GetFieldPascalName }} string
{{- end }}
}{
{{- range .LogFields }}
	{{ .GetFieldPascalName }}: "{{ .Name }}",
{{- end }}
}

// fieldOrder 记录字段在 YAML 中的顺序
var fieldOrder = map[string]int{
{{- range $index, $field := .LogFields }}
	fieldKeys.{{ $field.GetFieldPascalName }}: {{ $index }},
{{- end }}
}

// SortableField 表示可排序的日志字段
type SortableField struct {
	Field logx.LogField
	Order int
}

// sortFields 按 YAML 定义的顺序对字段进行排序
func sortFields(fields []SortableField) []logx.LogField {
	sort.Slice(fields, func(i, j int) bool {
		return fields[i].Order < fields[j].Order
	})
	result := make([]logx.LogField, len(fields))
	for i, f := range fields {
		result[i] = f.Field
	}
	return result
}

{{- range .LogFields }}

// {{ .GetFieldPascalName }} {{ .Comment }}
type {{ .GetFieldPascalName }} {{ .Type }}

// W{{ .GetFieldPascalName }} 创建{{ .Comment }}日志字段
func W{{ .GetFieldPascalName }}(v {{ .Type }}) logx.LogField {
	return logx.Field(fieldKeys.{{ .GetFieldPascalName }}, {{ .GetFieldPascalName }}(v))
}
{{- if .Mask }}

// MaskSensitive 实现 Sensitive 接口，对{{ .Comment }}进行脱敏
func (v {{ .GetFieldPascalName }}) MaskSensitive() any {
	return mask{{ .GetFieldPascalName }}({{ .Type }}(v))
}
{{- end }}
{{- end }}

// LogBuilder 用于链式构建日志字段
type LogBuilder struct {
	ctx     context.Context
	content string
	fields  []SortableField
}

{{- range .LogFields }}

// W{{ .GetFieldPascalName }} 添加{{ .Comment }}字段
func (b *LogBuilder) W{{ .GetFieldPascalName }}(v {{ .Type }}) *LogBuilder {
	b.fields = append(b.fields, SortableField{
		Field: W{{ .GetFieldPascalName }}(v),
		Order: fieldOrder[fieldKeys.{{ .GetFieldPascalName }}],
	})
	return b
}
{{- end }}

// L 创建一个日志构建器
// 使用 .Debugs(), .Infos(), .Errors(), .Slows() 方法会按 YAML 字段顺序自动排序
// 使用 .Debug(), .Info(), .Error(), .Slow() 方法保持字段添加顺序，不自动排序
func L(ctx context.Context, content string) *LogBuilder {
	return &LogBuilder{
		ctx:     ctx,
		content: content,
		fields:  make([]SortableField, 0),
	}
}

// Debug 输出 Debug 级别日志（不排序，保持字段添加顺序）
func (b *LogBuilder) Debug() {
	fields := make([]logx.LogField, len(b.fields))
	for i, f := range b.fields {
		fields[i] = f.Field
	}
	logc.Debugw(b.ctx, b.content, fields...)
}

// Debugs 输出 Debug 级别日志（按 YAML 字段顺序自动排序）
func (b *LogBuilder) Debugs() {
	logc.Debugw(b.ctx, b.content, sortFields(b.fields)...)
}

// Info 输出 Info 级别日志（不排序，保持字段添加顺序）
func (b *LogBuilder) Info() {
	fields := make([]logx.LogField, len(b.fields))
	for i, f := range b.fields {
		fields[i] = f.Field
	}
	logc.Infow(b.ctx, b.content, fields...)
}

// Infos 输出 Info 级别日志（按 YAML 字段顺序自动排序）
func (b *LogBuilder) Infos() {
	logc.Infow(b.ctx, b.content, sortFields(b.fields)...)
}

// Error 输出 Error 级别日志（不排序，保持字段添加顺序）
func (b *LogBuilder) Error() {
	fields := make([]logx.LogField, len(b.fields))
	for i, f := range b.fields {
		fields[i] = f.Field
	}
	logc.Errorw(b.ctx, b.content, fields...)
}

// Errors 输出 Error 级别日志（按 YAML 字段顺序自动排序）
func (b *LogBuilder) Errors() {
	logc.Errorw(b.ctx, b.content, sortFields(b.fields)...)
}

// Slow 输出 Slow 级别日志（不排序，保持字段添加顺序）
func (b *LogBuilder) Slow() {
	fields := make([]logx.LogField, len(b.fields))
	for i, f := range b.fields {
		fields[i] = f.Field
	}
	logc.Sloww(b.ctx, b.content, fields...)
}

// Slows 输出 Slow 级别日志（按 YAML 字段顺序自动排序）
func (b *LogBuilder) Slows() {
	logc.Sloww(b.ctx, b.content, sortFields(b.fields)...)
}
`

// LogFuncMap 返回日志字段模板函数映射
func LogFuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascal": config.ToPascal,
		"toLower":  strings.ToLower,
		"toCamel":  config.ToCamel,
	}
}
