// Package template 提供日志字段代码生成的模板定义
package template

import (
	"strings"
	"text/template"

	"github.com/yuan-shuo/zerotele/internal/config"
)

// LogFieldsTemplate 是生成日志字段代码的模板字符串
const LogFieldsTemplate = `// Code generated by zerotele; DO NOT EDIT.
// zerotele {{ .Version }}

package {{ .PackageName }}

import (
	"github.com/zeromicro/go-zero/core/logx"
)

// fieldKeys 日志字段名常量（与类型名保持一致）
var fieldKeys = struct {
{{- range .LogFields }}
	{{ .GetFieldPascalName }} string
{{- end }}
}{
{{- range .LogFields }}
	{{ .GetFieldPascalName }}: "{{ .Name }}",
{{- end }}
}

{{- range .LogFields }}

// {{ .GetFieldPascalName }} {{ .Comment }}
type {{ .GetFieldPascalName }} {{ .Type }}

// W{{ .GetFieldPascalName }} 创建{{ .Comment }}日志字段
func W{{ .GetFieldPascalName }}(v {{ .Type }}) logx.LogField {
	return logx.Field(fieldKeys.{{ .GetFieldPascalName }}, {{ .GetFieldPascalName }}(v))
}
{{- if .Mask }}

// MaskSensitive 实现 Sensitive 接口，对{{ .Comment }}进行脱敏
func (v {{ .GetFieldPascalName }}) MaskSensitive() any {
	return mask{{ .GetFieldPascalName }}({{ .Type }}(v))
}
{{- end }}
{{- end }}
`

// LogFuncMap 返回日志字段模板函数映射
func LogFuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascal": config.ToPascal,
		"toLower":  strings.ToLower,
		"toCamel":  config.ToCamel,
	}
}
