// Package template 提供代码生成的模板定义和辅助函数
package template

import (
	"strings"
	"text/template"

	"github.com/yuan-shuo/zerotele/internal/config"
)

// MetricsTemplate 是生成指标代码的模板字符串
const MetricsTemplate = `// Code generated by zerotele; DO NOT EDIT.
// zerotele {{ .Version }}

package {{ .PackageName }}

import (
    "github.com/zeromicro/go-zero/core/metric"
)

// ========== Builder ==========

// builder 是指标构建器的内部实现
type builder struct {
    // service 是观测服务名，作为 service 标签的值
    service string
}

// newBuilder 创建一个新的指标构建器
func newBuilder(service string) *builder {
    return &builder{service: service}
}

func (b *builder) newCounterVec(name, help string, labels []string) metric.CounterVec {
    return metric.NewCounterVec(&metric.CounterVecOpts{
        Name:   name,
        Help:   help,
        Labels: labels,
    })
}

func (b *builder) newGaugeVec(name, help string, labels []string) metric.GaugeVec {
    return metric.NewGaugeVec(&metric.GaugeVecOpts{
        Name:   name,
        Help:   help,
        Labels: labels,
    })
}

func (b *builder) newHistogramVec(name, help string, buckets []float64, labels []string) metric.HistogramVec {
    return metric.NewHistogramVec(&metric.HistogramVecOpts{
        Name:    name,
        Help:    help,
        Buckets: buckets,
        Labels:  labels,
    })
}

// ========== Enums ==========
{{- range $metric := .Metrics }}
{{- range $label := $metric.Labels }}
{{- if $label.IsEnum }}
// {{ $metric.Name | toPascal }}{{ $label.Name | toPascal }} 是指标 [{{ $metric.Name }}] 的标签 [{{ $label.Name }}] 的枚举类型
// 用于将指标 {{ $metric.Name }} 的 {{ $label.Name }} 标签设置为以下值之一：{{ join $label.Vals ", " }}
type {{ $metric.Name | toPascal }}{{ $label.Name | toPascal }} interface {
    {{ $metric.Name | camelCase }}{{ $label.Name | camelCase }}Value() string
}

type {{ $metric.Name | camelCase }}{{ $label.Name | camelCase }}Impl struct{ v string }

func (s {{ $metric.Name | camelCase }}{{ $label.Name | camelCase }}Impl) {{ $metric.Name | camelCase }}{{ $label.Name | camelCase }}Value() string { return s.v }

var (
{{- range $val := $label.Vals }}
    // {{ $metric.Name | toPascal }}{{ $label.Name | toPascal }}{{ $val | toPascal }} 将指标 [{{ $metric.Name }}] 的 [{{ $label.Name }}] 标签设置为 "{{ $val }}"
    {{ $metric.Name | toPascal }}{{ $label.Name | toPascal }}{{ $val | toPascal }} {{ $metric.Name | toPascal }}{{ $label.Name | toPascal }} = {{ $metric.Name | camelCase }}{{ $label.Name | camelCase }}Impl{"{{ $val }}"}
{{- end }}
)
{{- end }}
{{- end }}
{{- end }}

// ========== Metrics Struct ==========

// Metrics 包含所有生成的指标实例
// 通过 NewMetrics() 创建，所有指标共享相同的 service 标签值 [{{ .Service }}]
type Metrics struct {
    {{- range .Metrics }}
    // {{ .Name | toPascal }} 对应指标：{{ .Name }}{service="{{ $.Service }}"{{ range .Labels }}, {{ .Name }}=...{{ end }}}
    //
    // 	- 类型: {{ .Type }}
    // 	- 说明: {{ .Help }}
    {{ .Name | toPascal }} *{{ .Name | toPascal }}Metric
    {{- end }}
}

// NewMetrics 创建一个新的 Metrics 实例
// 所有指标将自动带有 service="{{ .Service }}" 的标签
func NewMetrics() *Metrics {
    b := newBuilder("{{ .Service }}")
    m := &Metrics{}
    {{- range .Metrics }}
    m.{{ .Name | toPascal }} = new{{ .Name | toPascal }}Metric(b)
    {{- end }}
    return m
}

{{- range $metric := .Metrics }}
// ========== {{ $metric.Name }} ==========

// {{ $metric.Name | toPascal }}Metric 是指标 [{{ $metric.Name }}] 的封装
// Prometheus 格式：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}}
// 类型: {{ $metric.Type }}
// 说明: {{ $metric.Help }}
// 标签:{{ range $metric.Labels }} {{ .Name }}{{ end }}
type {{ $metric.Name | toPascal }}Metric struct {
    {{- if eq $metric.Type "counter" }}
    metric.CounterVec
    {{- else if eq $metric.Type "gauge" }}
    metric.GaugeVec
    {{- else if eq $metric.Type "histogram" }}
    metric.HistogramVec
    {{- end }}
}

func new{{ $metric.Name | toPascal }}Metric(b *builder) *{{ $metric.Name | toPascal }}Metric {
    labels := []string{"service"{{ range $metric.Labels }}, "{{ .Name }}"{{ end }}}
    return &{{ $metric.Name | toPascal }}Metric{
        {{- if eq $metric.Type "counter" }}
        CounterVec: b.newCounterVec("{{ $metric.Name }}", "{{ $metric.Help }}", labels),
        {{- else if eq $metric.Type "gauge" }}
        GaugeVec: b.newGaugeVec("{{ $metric.Name }}", "{{ $metric.Help }}", labels),
        {{- else if eq $metric.Type "histogram" }}
        HistogramVec: b.newHistogramVec("{{ $metric.Name }}", "{{ $metric.Help }}", {{ printf "%#v" $metric.Buckets }}, labels),
        {{- end }}
    }
}
{{- if eq $metric.Type "counter" }}
{{- if hasMethod $metric.Methods "inc" }}

// Inc 将计数器值加 1
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} += 1
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Inc({{ labelParams $metric.Name $metric.Labels }}) {
    m.CounterVec.Inc("{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- if hasMethod $metric.Methods "add" }}

// Add 将计数器值增加 v
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} += v
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Add(v float64, {{ labelParams $metric.Name $metric.Labels }}) {
    m.CounterVec.Add(v, "{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- else if eq $metric.Type "gauge" }}
{{- if hasMethod $metric.Methods "set" }}

// Set 设置仪表盘的值
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} = v
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Set(v float64, {{ labelParams $metric.Name $metric.Labels }}) {
    m.GaugeVec.Set(v, "{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- if hasMethod $metric.Methods "inc" }}

// Inc 将仪表盘值加 1
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} += 1
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Inc({{ labelParams $metric.Name $metric.Labels }}) {
    m.GaugeVec.Inc("{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- if hasMethod $metric.Methods "dec" }}

// Dec 将仪表盘值减 1
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} -= 1
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Dec({{ labelParams $metric.Name $metric.Labels }}) {
    m.GaugeVec.Dec("{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- else if eq $metric.Type "histogram" }}
{{- if hasMethod $metric.Methods "observe" }}

// Observe 记录一个观测值
// 生成的指标：{{ $metric.Name }}{service="{{ $.Service }}"{{ range $metric.Labels }}, {{ .Name }}=...{{ end }}} 记录值 v
// 参数说明：{{ range $metric.Labels }}
//   - {{ .Name }}: {{ if .IsEnum }}可用变量：{{ enumVars $metric.Name .Name .Vals }}{{ else }}任意字符串{{ end }}{{ end }}
func (m *{{ $metric.Name | toPascal }}Metric) Observe(v int64, {{ labelParams $metric.Name $metric.Labels }}) {
    m.HistogramVec.Observe(v, "{{ $.Service }}"{{ range $metric.Labels }}, {{ labelArg . $metric.Name }}{{ end }})
}
{{- end }}
{{- end }}
{{- end }}
`

// FuncMap 返回模板函数映射
func FuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascal":    config.ToPascal,
		"camelCase":   config.ToCamel,
		"hasMethod":   HasMethod,
		"isEnum":      IsEnum,
		"join":        Join,
		"enumVars":    EnumVars,
		"labelParams": LabelParams,
		"labelArg":    LabelArg,
	}
}

// HasMethod 检查方法列表中是否包含指定方法
func HasMethod(methods []string, target string) bool {
	for _, m := range methods {
		if m == target {
			return true
		}
	}
	return false
}

// IsEnum 检查标签值是否是枚举（不是通配符 *）
func IsEnum(vals []string) bool {
	if len(vals) == 0 {
		return false
	}
	for _, v := range vals {
		if v == "*" {
			return false
		}
	}
	return true
}

// Join 将字符串切片用分隔符连接
func Join(strs []string, sep string) string {
	return strings.Join(strs, sep)
}

// EnumVars 生成所有枚举变量名
func EnumVars(metricName, labelName string, vals []string) string {
	vars := make([]string, len(vals))
	for i, v := range vals {
		vars[i] = config.ToPascal(metricName) + config.ToPascal(labelName) + config.ToPascal(v)
	}
	return strings.Join(vars, ", ")
}

// LabelParams 生成标签参数字符串，使用枚举类型或 string
func LabelParams(metricName string, labels []config.Label) string {
	if len(labels) == 0 {
		return ""
	}
	params := make([]string, len(labels))
	for i, label := range labels {
		if label.IsEnum() {
			params[i] = label.Name + " " + config.ToPascal(metricName) + config.ToPascal(label.Name)
		} else {
			params[i] = label.Name + " string"
		}
	}
	return strings.Join(params, ", ")
}

// LabelArg 生成标签参数调用
func LabelArg(label config.Label, metricName string) string {
	if label.IsEnum() {
		return label.Name + "." + config.ToCamel(metricName) + config.ToCamel(label.Name) + "Value()"
	}
	return label.Name
}
