// Package template 提供代码生成的模板定义和辅助函数
package template

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/yuan-shuo/zerotele/internal/config"
)

// LogFieldsTemplate 是生成日志字段代码的模板字符串
const LogFieldsTemplate = `// Code generated by zerotele; DO NOT EDIT.
package {{ .PackageName }}

import (
	"github.com/zeromicro/go-zero/core/logx"
)

// fieldKeys 日志字段名常量（与类型名保持一致）
var fieldKeys = struct {
{{- range .Fields }}
	{{ .GetFieldPascalName }} string
{{- end }}
}{
{{- range .Fields }}
	{{ .GetFieldPascalName }}: "{{ .Name }}",
{{- end }}
}

{{- range .Fields }}

// {{ .GetFieldPascalName }} {{ .Comment }}
type {{ .GetFieldPascalName }} {{ .Type }}

// W{{ .GetFieldPascalName }} 创建{{ .Comment }}日志字段
func W{{ .GetFieldPascalName }}(v {{ .Type }}) logx.LogField {
	return logx.Field(fieldKeys.{{ .GetFieldPascalName }}, {{ .GetFieldPascalName }}(v))
}
{{- if .Mask }}

// MaskSensitive 实现 Sensitive 接口，对{{ .Comment }}进行脱敏
func (v {{ .GetFieldPascalName }}) MaskSensitive() any {
	return mask{{ .GetFieldPascalName }}({{ .Type }}(v))
}
{{- end }}
{{- end }}
`

// MetricsTemplate 是生成指标代码的模板字符串
const MetricsTemplate = `// Code generated by zerotele; DO NOT EDIT.
package {{ .PackageName }}

import (
	"github.com/zeromicro/go-zero/core/metric"
)

// MetricsManager 管理所有指标
type MetricsManager struct {
{{- range .Metrics }}
	{{ .GetMetricPascalName }} *{{ .GetMetricPascalName }}Metric
{{- end }}
}

// NewMetricsManager 创建指标管理器
func NewMetricsManager() *MetricsManager {
	namespace := "{{ .Service }}"
	return &MetricsManager{
{{- range .Metrics }}
		{{ .GetMetricPascalName }}: new{{ .GetMetricPascalName }}Metric(namespace),
{{- end }}
	}
}

{{- range $metric := .Metrics }}
{{- $metricName := $metric.GetMetricPascalName }}

// ========== {{ $metricName }} ==========

// {{ $metricName }}Metric {{ $metric.Help }}
type {{ $metricName }}Metric struct {
	vec metric.{{ $metric.Type | metricType }}Vec
}

// new{{ $metricName }}Metric 创建 {{ $metric.Name }} 指标
func new{{ $metricName }}Metric(namespace string) *{{ $metricName }}Metric {
	return &{{ $metricName }}Metric{
		vec: metric.New{{ $metric.Type | metricType }}Vec(&metric.{{ $metric.Type | metricType }}VecOpts{
			Namespace: namespace,
			Subsystem: "",
			Name:      "{{ $metric.Name }}",
			Help:      "{{ $metric.Help }}",
			{{- if eq $metric.Type "histogram" }}
			Buckets:   {{ $metric.Buckets | goFloat64Slice }},
			{{- end }}
			Labels:    {{ $metric.Labels | labelNames }},
		}),
	}
}
{{- range $method := $metric.Methods }}
{{- if eq $method "inc" }}

// Inc 增加计数器
func (m *{{ $metricName }}Metric) Inc({{ $metric.Labels | labelParams }}) {
	m.vec.Inc({{ $metric.Labels | labelArgs }})
}
{{- end }}
{{- if eq $method "add" }}

// Add 增加指定值
func (m *{{ $metricName }}Metric) Add(v float64, {{ $metric.Labels | labelParams }}) {
	m.vec.Add(v, {{ $metric.Labels | labelArgs }})
}
{{- end }}
{{- if eq $method "set" }}

// Set 设置仪表盘值
func (m *{{ $metricName }}Metric) Set(v float64, {{ $metric.Labels | labelParams }}) {
	m.vec.Set(v, {{ $metric.Labels | labelArgs }})
}
{{- end }}
{{- if eq $method "dec" }}

// Dec 减少仪表盘值
func (m *{{ $metricName }}Metric) Dec({{ $metric.Labels | labelParams }}) {
	m.vec.Dec({{ $metric.Labels | labelArgs }})
}
{{- end }}
{{- if eq $method "observe" }}

// Observe 观察直方图值
func (m *{{ $metricName }}Metric) Observe(v float64, {{ $metric.Labels | labelParams }}) {
	m.vec.Observe(v, {{ $metric.Labels | labelArgs }})
}
{{- end }}
{{- end }}
{{- end }}
`

// FuncMap 返回模板函数映射
func FuncMap() template.FuncMap {
	return template.FuncMap{
		"toPascal":       ToPascal,
		"toLower":        strings.ToLower,
		"metricType":     metricType,
		"labelNames":     labelNames,
		"labelParams":    labelParams,
		"labelArgs":      labelArgs,
		"goFloat64Slice": goFloat64Slice,
	}
}

// ToPascal 将 snake_case 转换为 PascalCase
func ToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

// metricType 返回指标类型的 PascalCase 形式
func metricType(t string) string {
	switch t {
	case "counter":
		return "Counter"
	case "gauge":
		return "Gauge"
	case "histogram":
		return "Histogram"
	default:
		return "Counter"
	}
}

// labelNames 生成标签名称数组
func labelNames(labels []config.LabelConfig) string {
	if len(labels) == 0 {
		return "nil"
	}
	var parts []string
	for _, l := range labels {
		parts = append(parts, fmt.Sprintf("%q", l.Name))
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// labelParams 生成标签参数列表
func labelParams(labels []config.LabelConfig) string {
	if len(labels) == 0 {
		return ""
	}
	var parts []string
	for _, l := range labels {
		parts = append(parts, fmt.Sprintf("%s string", l.Name))
	}
	return strings.Join(parts, ", ")
}

// labelArgs 生成标签参数调用
func labelArgs(labels []config.LabelConfig) string {
	if len(labels) == 0 {
		return ""
	}
	var parts []string
	for _, l := range labels {
		parts = append(parts, l.Name)
	}
	return strings.Join(parts, ", ")
}

// goFloat64Slice 生成 Go 的 float64 切片字面量
func goFloat64Slice(buckets []float64) string {
	if len(buckets) == 0 {
		return "nil"
	}
	var parts []string
	for _, b := range buckets {
		parts = append(parts, fmt.Sprintf("%g", b))
	}
	return "[]float64{" + strings.Join(parts, ", ") + "}"
}
